### ISSUE TITLE
issues running thing-it

### ISSUE THREAD

**Issue by brettnreno** [marcgille/thing-it-device-bacnet#1]
I've been working over a day now trying to launch thing-it.  I tried installing it on a pi I already had running with no luck, so I signed up and downloaded the rpi image.  Now that I have it loaded on a pi 3, I still have no luck.  When I execute "tin run" I get this error

tin run

No options file in start directory [/home/pi/bacnet-test]. Using defaults.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/usr/local/lib/node_modules/thing-it-node/node_modules/express/lib/application.js:617:24)
    at Object.run (/usr/local/lib/node_modules/thing-it-node/bin/thing-it-node.js:261:10)
    at runCommand (/usr/local/lib/node_modules/thing-it-node/node_modules/yargs/index.js:620:40)
    at parseArgs (/usr/local/lib/node_modules/thing-it-node/node_modules/yargs/index.js:536:9)
    at Object.Argv.Object.defineProperty.get [as argv] (/usr/local/lib/node_modules/thing-it-node/node_modules/yargs/index.js:499:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/thing-it-node/bin/thing-it-node.js:26:5)

Is there anywhere I can get a crash course on this?  Thanks

**Comment by marcgille** [comment]
brett, happy to help. i assume you have run tin init before?

another remark: we have just started pushing the bacnet code and if you are intending to work with it: this will be a couple of weeks before this is possible. we may need to indicate this more clearly in the thing-it-device-bacnet readme. apologies for any inconvenience.
